<?php

use Illuminate\Database\Seeder;

class LmocsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lmocs')->delete();
        
        \DB::table('lmocs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '4070',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3024',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '4477',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3023',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3710',
                'color' => 0,
                'quantity' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3460',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3021',
                'color' => 0,
                'quantity' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3795',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3031',
                'color' => 0,
                'quantity' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '6141',
                'color' => 0,
                'quantity' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '61252',
                'color' => 0,
                'quantity' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '60478',
                'color' => 0,
                'quantity' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '4488',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '54200',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '85984',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '92946',
                'color' => 0,
                'quantity' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '13269',
                'color' => 0,
                'quantity' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '4599a',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '63864',
                'color' => 0,
                'quantity' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '11209',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '18977',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '11208',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '18976',
                'color' => 0,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '99774',
                'color' => 72,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '54200',
                'color' => 72,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '12825',
                'color' => 72,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '99781',
                'color' => 71,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3023',
                'color' => 71,
                'quantity' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '60897',
                'color' => 71,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '10247',
                'color' => 71,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '44728',
                'color' => 4,
                'quantity' => 6,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3622',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3937',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3938',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '98282',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '50745',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '6231',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3024',
                'color' => 4,
                'quantity' => 7,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3023',
                'color' => 4,
                'quantity' => 12,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3623',
                'color' => 4,
                'quantity' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3666',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '2420',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3021',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3795',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '6019',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3794a',
                'color' => 4,
                'quantity' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '63868',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '60478',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '87580',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '61409',
                'color' => 4,
                'quantity' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '54200',
                'color' => 4,
                'quantity' => 13,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '85984',
                'color' => 4,
                'quantity' => 8,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '11477',
                'color' => 4,
                'quantity' => 4,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '15068',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3070b',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3069b',
                'color' => 4,
                'quantity' => 9,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3068b',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '87079',
                'color' => 4,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3024',
                'color' => 70,
                'quantity' => 3,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3749',
                'color' => 19,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3024',
                'color' => 47,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '3622',
                'color' => 15,
                'quantity' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'namemoc' => 'countach',
                'user_id' => 2,
                'part' => '2436',
                'color' => 14,
                'quantity' => 2,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}