<?php

use Illuminate\Database\Seeder;

class LpartsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lparts')->delete();
        
        \DB::table('lparts')->insert(array (
            0 => 
            array (
                'id' => 3,
                'part_num' => '2420',
                'description' => 'Plate 2 x 2 Corner',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            1 => 
            array (
                'id' => 4,
                'part_num' => '2431',
                'description' => 'Tile 1 x 4 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            2 => 
            array (
                'id' => 5,
                'part_num' => '2436',
                'description' => 'Bracket 1 x 2 - 1 x 4 [Square Corners]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            3 => 
            array (
                'id' => 6,
                'part_num' => '2555',
                'description' => 'Tile Special 1 x 1 with Clip and Straight Tips',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            4 => 
            array (
                'id' => 7,
                'part_num' => '2569',
                'description' => 'Antenna Whip 8H',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            5 => 
            array (
                'id' => 8,
                'part_num' => '2711',
                'description' => 'Technic Plate 1 x 5 with Toothed Ends_ 2 Studs and Center Axle Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            6 => 
            array (
                'id' => 9,
                'part_num' => '2719',
                'description' => 'Technic Plate 1 x 10 with Toothed Ends',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            7 => 
            array (
                'id' => 10,
                'part_num' => '2730',
                'description' => 'Technic Brick 1 x 10 [9 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            8 => 
            array (
                'id' => 11,
                'part_num' => '2825',
                'description' => 'Technic Beam 1 x 4 Thin with Stud Connector',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            9 => 
            array (
                'id' => 12,
                'part_num' => '2853',
                'description' => 'Technic Engine Crankshaft',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            10 => 
            array (
                'id' => 13,
                'part_num' => '2875',
                'description' => 'Slope 45° 2 x 6 x 2/3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            11 => 
            array (
                'id' => 14,
                'part_num' => '2905',
                'description' => 'Technic Beam Triangle Thin [Type I]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            12 => 
            array (
                'id' => 15,
                'part_num' => '3001',
                'description' => 'Brick 2 x 4',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            13 => 
            array (
                'id' => 16,
                'part_num' => '3002',
                'description' => 'Brick 2 x 3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            14 => 
            array (
                'id' => 17,
                'part_num' => '3003',
                'description' => 'Brick 2 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            15 => 
            array (
                'id' => 18,
                'part_num' => '3004',
                'description' => 'Brick 1 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            16 => 
            array (
                'id' => 19,
                'part_num' => '3005',
                'description' => 'Brick 1 x 1',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            17 => 
            array (
                'id' => 20,
                'part_num' => '3010',
                'description' => 'Brick 1 x 4',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            18 => 
            array (
                'id' => 21,
                'part_num' => '3021',
                'description' => 'Plate 2 x 3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            19 => 
            array (
                'id' => 22,
                'part_num' => '3022',
                'description' => 'Plate 2 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            20 => 
            array (
                'id' => 23,
                'part_num' => '3023',
                'description' => 'Plate 1 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            21 => 
            array (
                'id' => 24,
                'part_num' => '3024',
                'description' => 'Plate 1 x 1',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            22 => 
            array (
                'id' => 25,
                'part_num' => '3031',
                'description' => 'Plate 4 x 4',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            23 => 
            array (
                'id' => 26,
                'part_num' => '3176',
                'description' => 'Plate Special 3 x 2 with Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            24 => 
            array (
                'id' => 27,
                'part_num' => '3460',
                'description' => 'Plate 1 x 8',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            25 => 
            array (
                'id' => 28,
                'part_num' => '3612',
                'description' => 'Arm Piece Straight with 2 and 3 Fingers',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            26 => 
            array (
                'id' => 29,
                'part_num' => '3622',
                'description' => 'Brick 1 x 3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            27 => 
            array (
                'id' => 30,
                'part_num' => '3623',
                'description' => 'Plate 1 x 3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            28 => 
            array (
                'id' => 31,
                'part_num' => '3665',
                'description' => 'Slope Inverted 45° 2 x 1',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            29 => 
            array (
                'id' => 32,
                'part_num' => '3666',
                'description' => 'Plate 1 x 6',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            30 => 
            array (
                'id' => 33,
                'part_num' => '3680',
                'description' => 'Turntable 2 x 2 Plate_ Base',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            31 => 
            array (
                'id' => 34,
                'part_num' => '3700',
                'description' => 'Technic Brick 1 x 2 [1 Hole]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            32 => 
            array (
                'id' => 35,
                'part_num' => '3701',
                'description' => 'Technic Brick 1 x 4 [3 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            33 => 
            array (
                'id' => 36,
                'part_num' => '3702',
                'description' => 'Technic Brick 1 x 8 [7 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            34 => 
            array (
                'id' => 37,
                'part_num' => '3709',
                'description' => 'Technic Plate 2 x 4 [3 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            35 => 
            array (
                'id' => 38,
                'part_num' => '3710',
                'description' => 'Plate 1 x 4',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            36 => 
            array (
                'id' => 39,
                'part_num' => '3713',
                'description' => 'Technic Bush',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            37 => 
            array (
                'id' => 40,
                'part_num' => '3737',
                'description' => 'Technic Axle 10',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            38 => 
            array (
                'id' => 41,
                'part_num' => '3738',
                'description' => 'Technic Plate 2 x 8 [7 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            39 => 
            array (
                'id' => 42,
                'part_num' => '3749',
                'description' => 'Technic Axle Pin without Friction Ridges Lengthwise',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            40 => 
            array (
                'id' => 43,
                'part_num' => '3795',
                'description' => 'Plate 2 x 6',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            41 => 
            array (
                'id' => 44,
                'part_num' => '3832',
                'description' => 'Plate 2 x 10',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            42 => 
            array (
                'id' => 45,
                'part_num' => '3894',
                'description' => 'Technic Brick 1 x 6 [5 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            43 => 
            array (
                'id' => 46,
                'part_num' => '3895',
                'description' => 'Technic Brick 1 x 12 [11 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            44 => 
            array (
                'id' => 47,
                'part_num' => '3937',
                'description' => 'Hinge Brick 1 x 2 Base',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            45 => 
            array (
                'id' => 48,
                'part_num' => '3938',
                'description' => 'Hinge Brick 1 x 2 Top Plate Thin',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            46 => 
            array (
                'id' => 49,
                'part_num' => '3941',
                'description' => 'Brick Round 2 x 2 with Axle Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            47 => 
            array (
                'id' => 50,
                'part_num' => '4019',
                'description' => 'Technic Gear 16 Tooth with Round Holes [Old Style]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            48 => 
            array (
                'id' => 51,
                'part_num' => '4070',
                'description' => 'Brick Special 1 x 1 with Headlight and No Slot',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            49 => 
            array (
                'id' => 52,
                'part_num' => '4143',
                'description' => 'Technic Gear 14 Tooth Bevel',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            50 => 
            array (
                'id' => 53,
                'part_num' => '4229',
                'description' => 'Engine_ Strakes_ 2 x 2 Thin Top Plate',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            51 => 
            array (
                'id' => 54,
                'part_num' => '4261',
                'description' => 'Technic_ Steering Arm',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            52 => 
            array (
                'id' => 55,
                'part_num' => '4477',
                'description' => 'Plate 1 x 10',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            53 => 
            array (
                'id' => 56,
                'part_num' => '4488',
                'description' => 'Plate Special 2 x 2 with Wheel Holder',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            54 => 
            array (
                'id' => 57,
                'part_num' => '4589',
                'description' => 'Cone 1 x 1 [No Top Groove]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            55 => 
            array (
                'id' => 58,
                'part_num' => '4716',
                'description' => 'Technic Worm Gear',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            56 => 
            array (
                'id' => 59,
                'part_num' => '4733',
                'description' => 'Brick Special 1 x 1 Studs on 4 Sides',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            57 => 
            array (
                'id' => 60,
                'part_num' => '6005',
                'description' => 'Brick Arch 1 x 3 x 2 Curved Top',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            58 => 
            array (
                'id' => 61,
                'part_num' => '6019',
                'description' => 'Plate Special 1 x 1 with Clip Horizontal [Thick U Clip]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            59 => 
            array (
                'id' => 62,
                'part_num' => '6141',
                'description' => 'Plate Round 1 x 1 with Solid Stud',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            60 => 
            array (
                'id' => 63,
                'part_num' => '6231',
                'description' => 'Panel 1 x 1 x 1 Corner',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            61 => 
            array (
                'id' => 64,
                'part_num' => '6536',
                'description' => 'Technic Axle and Pin Connector Perpendicular',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            62 => 
            array (
                'id' => 65,
                'part_num' => '6541',
                'description' => 'Technic Brick 1 x 1 with Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            63 => 
            array (
                'id' => 66,
                'part_num' => '6553',
            'description' => 'Axle Technic 1.5 with Perpendicular Axle Connector (Technic Pole Reverser Handle)',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            64 => 
            array (
                'id' => 67,
                'part_num' => '6558',
                'description' => 'Technic Pin Long with Friction Ridges Lengthwise',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            65 => 
            array (
                'id' => 68,
                'part_num' => '6589',
                'description' => 'Technic Gear 12 Tooth Bevel',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            66 => 
            array (
                'id' => 69,
                'part_num' => '6632',
                'description' => 'Technic Beam 1 x 3 Thin',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            67 => 
            array (
                'id' => 70,
                'part_num' => '6636',
                'description' => 'Tile 1 x 6 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            68 => 
            array (
                'id' => 71,
                'part_num' => '10247',
                'description' => 'Plate Special 2 x2 with 1 Pin Hole [Complete Underside Rib]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            69 => 
            array (
                'id' => 72,
                'part_num' => '11153',
                'description' => 'Slope Curved 4 x 1 No Studs [Stud Holder with Symmetric Ridges]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            70 => 
            array (
                'id' => 73,
                'part_num' => '11208',
                'description' => 'Wheel 14mm D. x 9.9mm with Centre Groove_ Fake Bolts and 6 Spokes',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            71 => 
            array (
                'id' => 74,
                'part_num' => '11209',
                'description' => 'Tyre 21 x 9.9',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            72 => 
            array (
                'id' => 75,
                'part_num' => '11477',
                'description' => 'Slope Curved 2 x 1 No Studs [1/2 Bow]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            73 => 
            array (
                'id' => 76,
                'part_num' => '12825',
                'description' => 'Tile Special 1 x 1 with Clip with Rounded Tips',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            74 => 
            array (
                'id' => 77,
                'part_num' => '13269',
                'description' => 'Slope 45° 6 x 4 Double / 33° [Train Roof]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            75 => 
            array (
                'id' => 78,
                'part_num' => '15068',
                'description' => 'Slope Curved 2 x 2 x 2/3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            76 => 
            array (
                'id' => 79,
                'part_num' => '18653',
                'description' => 'Brick 1x3x2 w. inside bow',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            77 => 
            array (
                'id' => 80,
                'part_num' => '18975',
                'description' => 'Brick Special 2 x 4 x 1 1/3 with Holes and 2 x 2 Cutout',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            78 => 
            array (
                'id' => 81,
                'part_num' => '18976',
                'description' => 'Wheel 18 x 12 with Axle Hole and Stud',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            79 => 
            array (
                'id' => 82,
                'part_num' => '18977',
                'description' => 'Tyre 24 x 12 Low Profile',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            80 => 
            array (
                'id' => 83,
                'part_num' => '21562',
                'description' => 'LEG SHELL W.BALL SNAP',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            81 => 
            array (
                'id' => 84,
                'part_num' => '27255',
            'description' => 'LEGO Rotor with 4.85 Hole (27255)',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            82 => 
            array (
                'id' => 85,
                'part_num' => '30292',
                'description' => 'Flag 7 x 3 with Rod',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            83 => 
            array (
                'id' => 86,
                'part_num' => '30552',
                'description' => 'Hinge Cylinder 1 x 2 Locking with 1 Finger and Axle Hole On Ends',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            84 => 
            array (
                'id' => 87,
                'part_num' => '30553',
                'description' => 'Hinge Cylinder 1 x 2 Locking with 2 Click Fingers and Axle Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            85 => 
            array (
                'id' => 88,
                'part_num' => '32002',
                'description' => 'Technic Pin 3/4',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            86 => 
            array (
                'id' => 89,
                'part_num' => '32009',
                'description' => 'Technic Beam 1 x 11.5 Double Bent Thick',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            87 => 
            array (
                'id' => 90,
                'part_num' => '32015',
                'description' => 'Technic Axle and Pin Connector Angled #5 - 112.5°',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            88 => 
            array (
                'id' => 91,
                'part_num' => '32018',
                'description' => 'Technic Brick 1 x 14 [13 Holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            89 => 
            array (
                'id' => 92,
                'part_num' => '32034',
                'description' => 'Technic Axle and Pin Connector Angled #2 - 180°',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            90 => 
            array (
                'id' => 93,
                'part_num' => '32039',
                'description' => 'Technic Axle Connector with Axle Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            91 => 
            array (
                'id' => 94,
                'part_num' => '32054',
                'description' => 'Technic Pin Long with Friction Ridges Lengthwise and Stop Bush',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            92 => 
            array (
                'id' => 95,
                'part_num' => '32062',
                'description' => 'Technic Axle 2 Notched',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            93 => 
            array (
                'id' => 96,
                'part_num' => '32184',
                'description' => 'Technic Axle and Pin Connector Perpendicular 3L with Centre Pin Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            94 => 
            array (
                'id' => 97,
                'part_num' => '32192',
                'description' => 'Technic Axle and Pin Connector Angled #4 - 135°',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            95 => 
            array (
                'id' => 98,
                'part_num' => '41677',
                'description' => 'Technic Beam 1 x 2 Thin',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            96 => 
            array (
                'id' => 99,
                'part_num' => '42003',
                'description' => 'Technic Axle and Pin Connector Perpendicular 3L with 2 Pin Holes',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            97 => 
            array (
                'id' => 100,
                'part_num' => '43093',
                'description' => 'Technic Axle Pin with Friction Ridges Lengthwise',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            98 => 
            array (
                'id' => 101,
                'part_num' => '44728',
                'description' => 'Bracket 1 x 2 - 2 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            99 => 
            array (
                'id' => 102,
                'part_num' => '50745',
                'description' => 'Mudguard 4 x 2 1/2 x 2 with Arch Round',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            100 => 
            array (
                'id' => 103,
                'part_num' => '50923',
                'description' => 'Technic Beam 1 x 2 with Ball Joint Angled',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            101 => 
            array (
                'id' => 104,
                'part_num' => '50950',
                'description' => 'Slope Curved 3 x 1 No Studs',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            102 => 
            array (
                'id' => 105,
                'part_num' => '54200',
            'description' => 'Slope 30° 1 x 1 x 2/3 (Cheese Slope)',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            103 => 
            array (
                'id' => 106,
                'part_num' => '59900',
                'description' => 'Cone 1 x 1 [Top Groove]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            104 => 
            array (
                'id' => 107,
                'part_num' => '60478',
                'description' => 'Plate Special 1 x 2 with Handle on End [Closed Ends]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            105 => 
            array (
                'id' => 108,
                'part_num' => '60897',
                'description' => 'Plate Special 1 x 1 with Clip Vertical [Thick Open O Clip]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            106 => 
            array (
                'id' => 109,
                'part_num' => '61252',
                'description' => 'Plate Special 1 x 1 with Clip Horizontal [Thick Open O Clip]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            107 => 
            array (
                'id' => 110,
                'part_num' => '61409',
                'description' => 'Slope 18° 2 x 1 x 2/3 with 4 Slots',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            108 => 
            array (
                'id' => 111,
                'part_num' => '61678',
                'description' => 'Slope Curved 4 x 1 No Studs [Stud Holder with Asymmetric Ridges]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            109 => 
            array (
                'id' => 112,
                'part_num' => '63864',
                'description' => 'Tile 1 x 3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            110 => 
            array (
                'id' => 113,
                'part_num' => '63868',
                'description' => 'Plate Special 1 x 2 with Clip Horizontal on End',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            111 => 
            array (
                'id' => 114,
                'part_num' => '64276',
                'description' => 'Beam 1 x 2 with Ball Joint Straight',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            112 => 
            array (
                'id' => 115,
                'part_num' => '85943',
                'description' => 'Technic Brick 1 x 2 with Hole and Dual Beam Extensions',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            113 => 
            array (
                'id' => 116,
                'part_num' => '85970',
                'description' => 'Slope Curved 10 x 1 [Asymmetric Inside Ridges]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            114 => 
            array (
                'id' => 117,
                'part_num' => '85984',
                'description' => 'Slope 30° 1 x 2 x 2/3',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            115 => 
            array (
                'id' => 118,
                'part_num' => '87079',
                'description' => 'Tile 2 x 4 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            116 => 
            array (
                'id' => 119,
                'part_num' => '87580',
            'description' => 'Plate Special 2 x 2 with Groove and Center Stud (Jumper)',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            117 => 
            array (
                'id' => 120,
                'part_num' => '90611',
                'description' => 'Hero Factory Arm / Leg with Ball Joint on Axle and Ball Socket',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            118 => 
            array (
                'id' => 121,
                'part_num' => '92946',
                'description' => 'Slope 45° 2 x 1 with 2/3 Cutout [Original Version]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            119 => 
            array (
                'id' => 122,
                'part_num' => '93571',
                'description' => 'Technic Axle Connector 2 x 3 with Ball Socket_ Open Lower Axle Holes',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            120 => 
            array (
                'id' => 123,
                'part_num' => '98282',
                'description' => 'Mudguard 4 x 2 1/2 x 1 with Arch Round',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            121 => 
            array (
                'id' => 124,
                'part_num' => '99774',
                'description' => 'Minifig Ski without Hinge',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            122 => 
            array (
                'id' => 125,
                'part_num' => '99780',
                'description' => 'Bracket 1 x 2 - 1 x 2 Inverted',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            123 => 
            array (
                'id' => 126,
                'part_num' => '99781',
                'description' => 'Bracket 1 x 2 - 1 x 2',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            124 => 
            array (
                'id' => 127,
                'part_num' => '2412b',
                'description' => 'Tile Special 1 x 2 Grille with Bottom Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            125 => 
            array (
                'id' => 128,
                'part_num' => '3040b',
                'description' => 'Slope 45° 2 x 1 with Bottom Pin',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            126 => 
            array (
                'id' => 129,
                'part_num' => '30554b',
                'description' => 'Hinge Cylinder 1 x 3 Locking with 1 Finger and 2 Fingers On Ends_ with Hole',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            127 => 
            array (
                'id' => 130,
                'part_num' => '3062b',
                'description' => 'Brick Round 1 x 1 Open Stud',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            128 => 
            array (
                'id' => 131,
                'part_num' => '3068b',
                'description' => 'Tile 2 x 2 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            129 => 
            array (
                'id' => 132,
                'part_num' => '3069b',
                'description' => 'Tile 1 x 2 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            130 => 
            array (
                'id' => 133,
                'part_num' => '3069bp05',
                'description' => 'Tile 1 x 2 with Black Grill Print',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            131 => 
            array (
                'id' => 134,
                'part_num' => '3070b',
                'description' => 'Tile 1 x 1 with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            132 => 
            array (
                'id' => 135,
                'part_num' => '32123b',
                'description' => 'Technic Bush 1/2 Smooth with Axle Hole Semi-Reduced',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            133 => 
            array (
                'id' => 136,
                'part_num' => '3648a',
                'description' => 'Technic Gear 24 Tooth [Old Style - Three axle holes]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            134 => 
            array (
                'id' => 137,
                'part_num' => '3650c',
                'description' => 'Technic Gear 24 Tooth Crown with Reinforcements [New Style]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            135 => 
            array (
                'id' => 138,
                'part_num' => '3794a',
            'description' => 'Plate Special 1 x 2 with 1 Stud without Groove (Jumper)',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            136 => 
            array (
                'id' => 139,
                'part_num' => '3839b',
                'description' => 'Plate Special 1 x 2 with Handles [Flat Ends / Low Attachment]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            137 => 
            array (
                'id' => 140,
                'part_num' => '4085a',
                'description' => 'Plate Special 1 x 1 with Clip Vertical [Thin Open O Clip]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            138 => 
            array (
                'id' => 141,
                'part_num' => '4275b',
                'description' => 'Hinge Plate 1 x 2 with 3 Fingers and Hollow Studs',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            139 => 
            array (
                'id' => 142,
                'part_num' => '4276a',
                'description' => 'Hinge Plate 1 x 2 with 2 Fingers and Solid Studs',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            140 => 
            array (
                'id' => 143,
                'part_num' => '44302a',
                'description' => 'Hinge Plate 1 x 2 Locking with 2 Fingers On End_ with Groove',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            141 => 
            array (
                'id' => 144,
                'part_num' => '4599a',
                'description' => 'Tap1 x1 with Hole in Spout',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            142 => 
            array (
                'id' => 145,
                'part_num' => '48729b',
                'description' => 'Bar 1L with Clip [Cut Edges and One Side Hole]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            143 => 
            array (
                'id' => 146,
                'part_num' => '6153a',
                'description' => 'Wedge 6 x 4 Cutout [No Stud Notches]',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
            144 => 
            array (
                'id' => 147,
                'part_num' => '6153b',
                'description' => 'Wedge 6 x 4 Cutout with Stud Notches',
                'cat_id' => 1,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'img_path_1' => '',
                'img_path_2' => '',
            ),
        ));
        
        
    }
}